### ISSUE TITLE
Add shipping information for websites

### ISSUE THREAD

**Issue by bryceeppler** [bryceeppler/snapcaster-backend#87]
Maybe somewhere when hovering over a tooltip can popup displaying shipping information for the relevant site.

**Comment by henry-minh** [comment]
We might be able to automate this? I remember in a previous project the shopify sites had shipping rate tokens that had this information but i'm not 100% sure how to grab each one automatically since I manually grabbed them in the past. I used to grab them manually but I can see if I can do that in the automated script im updating right now
